[tool.poetry]
name = "web-scraper-pp"
version = "0.1.0"
description = ""
authors = ["Kathy <yuxuan.zh.jade@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
